### ISSUE TITLE
Ground Truth Depth Map

### ISSUE THREAD

**Issue by DeepDeep123** [xy-guo/Learning-Monocular-Depth-by-Stereo#11]
Hi, Guo,

I am wondering which ground truth depth map you use for supervised fine-tuning and evaluation on KITTI dataset. Is the offical depth provided by KITTI or from [monodepth](https://github.com/mrharicot/monodepth/blob/master/utils/evaluation_utils.py). I am confused, which one shall we use? 

Thanks!

**Comment by xy-guo** [comment]
The official depth provided by RAW KITTI is in point cloud format, which cannot be directly used for training. The code from Monodepth projects the point cloud into a depth map to the left camera view. My code follows Monodepth and also projects the point cloud into a depth map in the left camera view. The only difference is that Monodepth utilizes LiDAR depth values, while I use the depth values in the camera view. You can check [this file](https://github.com/mrharicot/monodepth/blob/master/utils/evaluation_utils.py#L191) for the depth map generation.

**Comment by DeepDeep123** [comment]
Hi, Guo,

Thanks for your reply! I just find that KITTI now indeeds provide ground truth depth map [data_depth_annotated.zip](http://www.cvlibs.net/download.php?file=data_depth_annotated.zip), where ground truth maps are saved as 16bit PNG files. 

By the way, you use depth values in the camera view, does it mean that  *vel_depth* is set to be *False*?

Thanks!

**Comment by xy-guo** [comment]
I think the data_depth_annotated.zip is from the new KITTI Depth Prediction benchmark, while my paper is based on KITTI RAW data and the Eigen split. 

It is the same when you set vel_depth to False.
