### ISSUE TITLE
About The Dataset

### ISSUE THREAD

**Issue by jinjingyi** [xy-guo/Learning-Monocular-Depth-by-Stereo#2]
Thanks for your work. For the preparation of the dataset, can you give the relevant links and provide more detailed instructions?

**Comment by xy-guo** [comment]
You can first refer to the Monodepth GitHub repo for the preparation of KITTI dataset. For the Scene Flow datasets, you can first download all the tars (Finalpass and disparities of monkaa, flyingthings, driving) and then extract and place the folders according to the sceneflow_folder_structure.txt. For automatical script, I may update next week.

**Comment by jinjingyi** [comment]
Thanks for your response, I will try it as you said and look forward to your update.

**Comment by xy-guo** [comment]
README has been updated.
