### ISSUE TITLE
Does the camera baseline matter?

### ISSUE THREAD

**Issue by kwea123** [xy-guo/Learning-Monocular-Depth-by-Stereo#3]
In your experiments, you use only the scene flow dataset as synthetic data. I wonder if the camera baselines (and other intrinsic parameters) are the same across the three different scenarios (flying things, driving, monkaa)?
In my case, I want to train the proxy stereo net with scene flow and other additional data, does that degrade the network's performance due to different camera settings?

**Comment by xy-guo** [comment]
For stereo matching, it does not matter if the baselines are different because the outputs are disparity values (not dependent on the intrinsic parameters).

**Comment by kwea123** [comment]
Another question, have you tried training on more than 100 images (e.g. on the whole training set) in the supervised setting? If so, does it perform better?

**Comment by xy-guo** [comment]
Yes, I will perform better. But our paper mainly focuses on the cases when there is no ground truth or very little ground truth data.
