### ISSUE TITLE
what is the meaning of this code?

### ISSUE THREAD

**Issue by sazippe** [xy-guo/Learning-Monocular-Depth-by-Stereo#5]
Learning-Monocular-Depth-by-Stereo/models/monocular_model.py

110    def forward(self, x):
111       mean = Variable(torch.FloatTensor([0.485, 0.456, 0.406])).cuda()
112       var = Variable(torch.FloatTensor([0.229, 0.224, 0.225])).cuda()
113       x = (x - mean.view(1, -1, 1, 1)) / (var.view(1, -1, 1, 1))

Why is this done in monocular model, but does not done this in stereo model? Thank you.

**Comment by xy-guo** [comment]
I think you could get similar results after moving 111-113.

**Comment by kwea123** [comment]
It's data normalization but doesn't have much influence on the final performance.

**Comment by sazippe** [comment]
Thank you!
But why normalization is done only in monocular model? 
Is it because monocular model use pretrained vgg16 weight?

**Comment by xy-guo** [comment]
I think the normalization is not so important. You can add or remove the normalization for the mono/stereo models and the performance will not change.
