### ISSUE TITLE
Decoder training in main_distill_mono.py

### ISSUE THREAD

**Issue by kwea123** [xy-guo/Learning-Monocular-Depth-by-Stereo#8]
https://github.com/xy-guo/Learning-Monocular-Depth-by-Stereo/blob/3547a9e6f081177114e997e5986b2b546cee6109/main_distill_mono.py#L104

Here you train the decoder only for the first epoch. Why?

**Comment by xy-guo** [comment]
Only the encoder is initialized with ImageNet pretrained weights, while the decoder is randomly initialized. I hope to train the randomly initialized decoder for one epoch first, then the whole network. I think this could produce more robust model.

**Comment by kwea123** [comment]
Oh, I misunderstood that as "training the decoder only for the first epoch, and stop training it from the second epoch and on." Now it's clear and good.
