### ISSUE TITLE
Performance of `StereoNoFt` on Cityscapes

### ISSUE THREAD

**Issue by kwea123** [xy-guo/Learning-Monocular-Depth-by-Stereo#9]
In the paper you state "Stereo networks generalize much better and have smaller synthetic-to-real domain transfer problems."

When I tried `release-StereoNoFt.ckpt` on a Cityscapes stereo image pair, it produces the following result: (the image is resized to 1024x512 using `cv2.INTER_AREA`)
![image](https://user-images.githubusercontent.com/11364490/51286480-89904380-1a36-11e9-92c3-1d5904e5b254.png)
But on KITTI it's pretty good (image size 1280x384)
![image](https://user-images.githubusercontent.com/11364490/51286691-6023e780-1a37-11e9-93ef-fc12bccd6b51.png)

The monocular model `release-StereoUnsupFt-Mono-pt.ckpt` has the same phenomenon: bad on Cityscapes but good on KITTI. I also tried removing the car hood but without much improvement.
Could you please give us a guide on how to reproduce the result of Figure 7?

**Comment by xy-guo** [comment]
The precision is low for far away objects. I think you can try images which include more near objects like Fig.7?
